POST http://127.0.0.1:3000/api/tasks
Content-Type: application/json


[
    {
        "id": 300,
        "nombre": "ir de compras",
        "estado": "completado",
        "fecha-objetivo": "31/03/2026",
        "categoria": "general"
    },
    {
        "id": 301,
        "nombre": "ir de compras",
        "estado": "completado",
        "fecha-objetivo": "31/03/2026",
        "categoria": "general"
    }    
]

###
PUT http://127.0.0.1:3000/api/tasks/50
Content-Type: application/json

    {
        "nombre": "pepito"
    }